openapi: "3.0.0"
info:
  title: Hacker News Unofficial API
  version: 1.0.0
servers:
  - url: https://api.hackerwebapp.com
paths:
  /news:
    get:
      operationId: GetHackerNewsPage
      summary: Gets a complete page from Hacker News
      parameters:
        - name: page
          in: query
          description: Which page to get
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Items"
components:
  schemas:
    Item:
      type: object
      required:
        - id
        - title
        - points
        - user
        - time
        - time_ago
        - comments_count
        - type
        - url
        - domain
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        points:
          type: integer
          format: int32
        user:
          type: string
        time:
          type: number
          format: int64
        time_ago:
          type: string
        comments_count:
          type: integer
          format: int32
        type:
          type: string
        url:
          type: string
        domain:
          type: string

    Items:
      type: array
      items:
        $ref: "#/components/schemas/Item"
